### ISSUE TITLE
Occasional Crash on 'scaleImageForScrollViewTransitionFromBounds:'

### ISSUE THREAD

**Issue by ezathashim** [yuriiik/ISVImageScrollView#1]
I get the occasional crash:

 [ISVImageScrollView scaleImageForScrollViewTransitionFromBounds:toBounds:]
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

I think the line 101:

CGSize containedImageSizeOld = [self rectSizeForAspectRatio:self.imageAspectRatio
                                                   thatFitsSize:oldSize];

might be returning a zero size and further down the line, it becomes the denominator in a division.

I'm not sure if the fix should be done in 'rectSizeForAspectRatio:thatFitsSize:' or in 'scaleImageForScrollViewTransitionFromBounds'

**Comment by yuriiik** [comment]
Hello @ezathashim!

Thank you for reporting this. I'll investigate the issue and get back to you soon. Meanwhile if you could provide at least some steps to reproduce that would help a lot!

**Comment by ezathashim** [comment]
I can't reproduce it, but I do get the occasional crash report through HockeyApp. I have attached a crash report
[ImageScrollView_Crash.log](https://github.com/yuriiik/ISVImageScrollView/files/2402765/ImageScrollView_Crash.log)

**Comment by yuriiik** [comment]
@ezathashim sorry for delay and thank you for your pull request. It has been merged into the v0.1.2.
