### ISSUE TITLE
Not a real issue; just saying thanks!

### ISSUE THREAD

**Issue by tylerjames** [yuriiik/ISVImageScrollView#5]
This is not a real issue so feel free to delete it.

I just wanted to say thanks. 
I was having a really frustrating day trying to get this pinch/zoom/pan in a scrollview thing to work using constraints. I had it mostly working but there was always something weird with the content size or position, especially after rotating the screen. All the "tutorials" on how to do it were overly simplistic and didn't actually work very well.

I decided to try your code out and it worked perfectly. I adapted to work with any kind of UIView (as long as you pass an explicit aspect ratio) and it has worked great. Really saved my sanity!

Anyway, I tried looking you up on Twitter and I just saw that you're from Kiev. I hope you and your family are safe and are doing as well as you can, given the circumstances.

Take care dude and thanks again

**Comment by yuriiik** [comment]
@tylerjames thank you for your feedback, I really appreciate it! Feel free to contact me if you need any help.

PS: Yes, I'm from Kyiv. Not the easiest time indeed. Holding on.
